apiVersion: apps/v1
kind: Deployment
metadata:
  name: ck8sd
spec:
  replicas: 1
  selector:
    matchLabels:
      name: ck8sd
  template:
    metadata:
      labels:
        name: ck8sd
    spec:
      serviceAccountName: ck8sd
      containers:
        - name: ck8sd
          # Replace this with the built image name
          image: cswarm/ck8sd
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 200m
              memory: 512Mi
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "ck8sd"
