apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: ck8sd
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - services/finalizers
  - endpoints
  - persistentvolumeclaims
  - events
  - configmaps
  - secrets
  verbs:
  - '*'
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  - replicasets
  - statefulsets
  verbs:
  - '*'
- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  verbs:
  - get
  - create
- apiGroups:
  - apps
  resourceNames:
  - ck8sd
  resources:
  - deployments/finalizers
  verbs:
  - update
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
- apiGroups:
  - apps
  resources:
  - replicasets
  - deployments
  verbs:
  - get
- apiGroups:
  - computercraft.ck8sd.com
  resources:
  - '*'
  - computerpods
  - computerdeployments
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ck8sd-computers
rules:
- apiGroups:
  - computercraft.ck8sd.com
  resources:
  - computers
  verbs:
  - create
- apiGroups:
  - computercraft.ck8sd.com
  resources:
  - computers/status
  verbs:
  - patch
  - get
- apiGroups: [""]
  resources:
  - secrets
  - configmaps
  verbs:
  - get
- apiGroups:
  - computercraft.ck8sd.com
  resources:
  - computerpods
  verbs:
  - list
  - get
  - patch
  - update
- apiGroups:
  - computercraft.ck8sd.com
  resources:
  - computerpods/status
  verbs:
  - get
  - patch