apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: computerpods.computercraft.ck8sd.com
spec:
  additionalPrinterColumns:
  - JSONPath: .status.phase
    name: Status
    type: string
  - JSONPath: .status.assignedComputer
    name: Assigned
    type: string
  - JSONPath: .metadata.creationTimestamp
    description: CreationTimestamp is a timestamp representing the server time when
      this object was created. It is not guaranteed to be set in happens-before order
      across separate operations. Clients may not set this value. It is represented
      in RFC3339 form and is in UTC.
    name: Age
    type: date
  group: computercraft.ck8sd.com
  names:
    kind: ComputerPod
    listKind: ComputerPodList
    plural: computerpods
    singular: computerpod
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: ComputerPod is the Schema for the computerpods API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: ComputerPodSpec defines the desired state of ComputerPod
          properties:
            computerType:
              description: ComputerType is a type of computer to run on
              type: string
            url:
              description: URL is a URL to download source code from
              type: string
          type: object
        status:
          description: ComputerPodStatus represents information about the status of
            a computerpod. Status may trail the actual state of a system, especially
            if the node that hosts the computerpod cannot contact the control plane.
          properties:
            assignedComputer:
              description: AssignedComputer is the computer resource that this ComputerPod
                has been scheduled onto
              type: string
            message:
              description: A human readable message indicating details about why the
                computerpod is in this condition.
              type: string
            phase:
              description: PodPhase is a label for the condition of a pod at the current
                time.
              type: string
            reason:
              description: A brief CamelCase message indicating details about why
                the computerpod is in this state. e.g. 'Evicted'
              type: string
            startTime:
              description: RFC 3339 date and time at which the object was acknowledged
                by the Kubelet. This is before the Kubelet pulled the container image(s)
                for the pod.
              format: date-time
              type: string
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
