apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: computers.computercraft.ck8sd.com
spec:
  group: computercraft.ck8sd.com
  names:
    kind: Computer
    listKind: ComputerList
    plural: computers
    singular: computer
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: Computer is the Schema for the computers API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: ComputerSpec defines the desired state of Computer
          type: object
        status:
          description: ComputerStatus defines the observed state of Computer
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
